using System.Configuration;

namespace Portfolio.Shared.Repository
{
    public class Strings
    {
        public const string AddCoin = "Add coin";
        public const string AddCoinMessage = "Success! Coin was added to inventory.";
        public const string AddLowercase = "add";
        public const string AllLowercase = "all";
        public const string AzureAd = "AzureAd";
        public const string AzureAdScopes = "AzureAd:Scopes";
        public const string AzureFallbackUrl = "https://www.google.com/?q=azure";
        public const string AzureUrlKey = "AzureUrl";
        public const string BlazorUrlKey = "BlazorUrl";
        public const string BlazorFallbackUrl = "https://www.google.com/search?q=blazor";
        public const string BootstrapUrlKey = "BootstrapUrl";
        public const string BootstrapFallbackUrl = "https://www.google.com/?q=bootstrap";
        public const string Cancel = "Cancel";
        public const string Choose = "Choose";
        public const string CleanedQuestion = "Cleaned?";
        public const string CoinDetail = "Coin detail";
        public const string CoinLowercase = "coin";
        public const string Coins = "Coins";
        public const string CSharpUrlKey = "CSharpUrl";
        public const string CSharpFallbackUrl = "https://www.google.com/search?q=c%23";
        public const string CommandTimeout = "CommandTimeout";
        public const string CurrencyLowercase = "currency";
        public const string CurrentInventory = "Current inventory";
        public const string DefaultDateFormat = "mm-dd-yyyy";
        public const string DefaultConnection = "DefaultConnection";
        public const string Denomination = "Denomination";
        public const string DenominationLowercase = "denomination";
        public const string Description = "Description";
        public const string DotNetUrlKey = "DotNetUrl";
        public const string DotNetFallbackUrl = "https://www.google.com/?q=.net%207";
        public const string EmptyString = "";
        public const string ForSaleSoon = "For Sale Soon";
        public const string GetCoinByIdProc = "dbo.GetCoinById";
        public const string GetCoinsProc = "dbo.GetCoins";
        public const string GetDenominationsProc = "dbo.GetDenominations";
        public const string GetGradingCompaniesProc = "dbo.GetGradingCompanies";
        public const string GetMintByIdProc = "dbo.GetMintById";
        public const string GetMintsProc = "dbo.GetMints";
        public const string GetPurchaseDetailByIdProc = "dbo.GetPurchaseDetailById";
        public const string GithubUrlKey = "GithubUrl";
        public const string GithubFallbackUrl = "https://www.google.com/?q=github";
        public const string Grade = "Grade";
        public const string GradedBy = "Graded By";
        public const string Home = "Home";
        public const string IdOfTypeInt32 = "{id:int}";
        public const string IdOfTypeLong = "{id:long}";
        public const string InteropInitDatepicker = "interop.initDatepicker";
        public const string InventoryLowercase = "inventory";
        public const string JavascriptUrlKey = "JavascriptUrl";
        public const string JavascriptFallbackUrl = "https://www.google.com/?q=javascript";
        public const string ListPrice = "List price";
        public const string MapDataLocation = "MapDataLocation";
        public const string MapDetail = "Map detail";
        public const string MapsLowercase = "maps";
        public const string MapSearch = "Map search";
        public const string Mint = "Mint";
        public const string MintLowercase = "mint";
        public const string MintsLowercase = "mints";
        public const string No = "No";
        public const string NoInventory = "No inventory";
        public const string NotForSale = "Not For Sale";
        public const string PortfolioDotShared = "Portfolio.Shared";
        public const string PurchaseDate = "Purchase Date";
        public const string Quantity = "Quantity";
        public const string QuantityIsRequired = "Quantity is required";
        public const string QuantityMustBeAtLeastOne = "Quantity must be at least 1";
        public const string RequestRequiredMessage = "Request is required.";
        public const string ResumeUrlKey = "ResumeUrl";
        public const string ReturnToInventory = "Return to inventory";
        public const string Save = "Save";
        public const string SaveCoinProc = "dbo.SaveCoin";
        public const string SellerAddress = "Seller Address";
        public const string SellerName = "Seller Name";
        public const string Shipping = "Shipping";
        public const string Subtotal = "Subtotal";
        public const string Tax = "Tax";
        public const string UpdateLowercase = "update";
        public const string V1Lowercase = "v1";
        public const string Year = "Year";
        public const string Yes = "Yes";
        public const string Zero = "0";
    }
}
